### ISSUE TITLE
Edge Addons 内插件是否为官方版？

### ISSUE THREAD

**Issue by JedSunCN** [niuchaobo/acfun-helper#113]
Edge 扩展商店内上架了acfun-helper，请问是否为官方原版上架？
[https://microsoftedge.microsoft.com/addons/detail/acfun%E5%8A%A9%E6%89%8B/lbnimimllmcdmojehbgndnebjafgnjfk?hl=zh-CN](url)
如果是，请问作者是否能将此链接添加到REDME中，方便验证官方性？
谢谢！

**Comment by Sokwva** [comment]
是的，晚上我回去就加
