### ISSUE TITLE
能否在菜单栏用中键点开视频后不关闭弹窗?

### ISSUE THREAD

**Issue by ironstress** [niuchaobo/acfun-helper#124]
我想一次性浏览完更新的视频,把想看的视频都在后台打开再一个一个看过来,而不是"点开一个视频,看完,点击图标,滚动滚轮,点开,循环",
这样太累了,所以希望能加入这个功能
如果把这个功能看作是一个视频更新通知,哪有感觉太浪费了

**Comment by Sokwva** [comment]
如果想使用中键打开而不关闭popup，你可以试试使用firefox，因为本来popup的机制，它定位就不是具有持久性的窗口，所以在chromium内核的一系列浏览器上面（包括我测试过的edge chrome 360极速）点击了一个稿件之后会直接关闭。我尝试了在popup中右键菜单加入了稍后再看的功能来弥补，也只能暂时作为一个解决方法吧。我们没法修改浏览器内核，所以只能用这种方法，还请见谅。

**Comment by 15372843021** [comment]
> 如果想使用中键打开而不关闭popup，你可以试试使用firefox，因为本来popup的机制，它定位就不是具有持久性的窗口，所以在chromium内核的一系列浏览器上面（包括我测试过的edge chrome 360极速）点击了一个稿件之后会直接关闭。我尝试了在popup中右键菜单加入了稍后再看的功能来弥补，也只能暂时作为一个解决方法吧。我们没法修改浏览器内核，所以只能用这种方法，还请见谅。

试了下稍后再看这个功能,添加的方式太麻烦,不如在popup里视频封面右上角或者右下角多个稍后再看的选项.
打开稍后再看方法太奇葩了,在网站主页的历史记录右边或者popup多个按钮也可以的,而且打开后所有视频都会开始播放,还得一个一个暂停过来.
换firefox是不可能换firefox的,这辈子只能用edge了

**Comment by Sokwva** [comment]
也可以

**Comment by Sokwva** [comment]
考试太多了，群主又特别忙，先记下来，我有时间会做的

**Comment by Sokwva** [comment]
https://github.com/niuchaobo/acfun-helper/pull/123
https://github.com/Sokwva/acfun-helper/commit/4237365ba96d4461754de312b68749b71d6f7f0a

**Comment by DontBeAlarmed** [comment]
> > 如果想使用中键打开而不关闭popup，你可以试试使用firefox，因为本来popup的机制，它定位就不是具有持久性的窗口，所以在chromium内核的一系列浏览器上面（包括我测试过的edge chrome 360极速）点击了一个稿件之后会直接关闭。我尝试了在popup中右键菜单加入了稍后再看的功能来弥补，也只能暂时作为一个解决方法吧。我们没法修改浏览器内核，所以只能用这种方法，还请见谅。
> 
> 试了下稍后再看这个功能,添加的方式太麻烦,不如在popup里视频封面右上角或者右下角多个稍后再看的选项.
> 打开稍后再看方法太奇葩了,在网站主页的历史记录右边或者popup多个按钮也可以的,而且打开后所有视频都会开始播放,还得一个一个暂停过来.
> 换firefox是不可能换firefox的,这辈子只能用edge了

有了

**Comment by niuchaobo** [comment]
fixed
