### ISSUE TITLE
加入链接解析 更新release版本

### ISSUE THREAD

**Issue by catshitz** [niuchaobo/acfun-helper#125]
https://bit.ly/3lmF3Of

直接加载master会提示错误
<a href="https://pixhost.to/show/369/171819616_1.jpg"><img src="https://t47.pixhost.to/thumbs/369/171819616_1.jpg" alt="1.jpg" border="0"/></a>

**Comment by Sokwva** [comment]
这个错误是由于插件的消息机制调用没有回复的问题，不影响使用；

**Comment by Sokwva** [comment]
对于链接解析，我没有弄清楚在插件有下载功能的前提下有没有加入此功能的必要性
