### ISSUE TITLE
Web 直播 Feed 流时间戳显示问题

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#127]
例如当 21:03 的时候会显示 `[23:3]`，不太友好

**Comment by Sokwva** [comment]
@condy0919 你的意思是说要加上 0 变成 23::03 这种样式吗

**Comment by condy0919** [comment]
对的

**Comment by Sokwva** [comment]
https://github.com/niuchaobo/acfun-helper/commit/fb3cbdae9ac271604e2ece19092892ba12673dc9
应该差不多了

**Comment by condy0919** [comment]
感谢，等待火狐插件更新再看看。

不过这个 fix 方法有点奇怪，js 肯定是有对应的 datetime 库的，为啥还需要自己拼字符串？

**Comment by Sokwva** [comment]
@condy0919 火狐更新啊，那可能需要等到过年了，你看上次我的PR通过是啥时候，哎。
然后方法的话，我想过用day.js，但是看了下，我果然还是太懒了，就直接用拼接了。什么时候用到库了估计会一次性把其他要用到的地方全部改掉吧。

**Comment by condy0919** [comment]
目前观察到 Firefox 上的插件已经更新了
