### ISSUE TITLE
菜单界面有工具条滑动条遮挡

### ISSUE THREAD

**Issue by sde31c** [niuchaobo/acfun-helper#135]
![Snipaste_2021-03-01_16-36-14](https://user-images.githubusercontent.com/21274744/109471897-64db7680-7aac-11eb-87d9-7a809df83f4f.png)
菜单光标在非生放送栏，均会出现遮挡

**Comment by Sokwva** [comment]
请问这是什么浏览器，浏览器的什么版本，插件的来源，插件的版本呢，我看了下我的edge没有这种情况😶

**Comment by niuchaobo** [comment]
> 请问这是什么浏览器，浏览器的什么版本，插件的来源，插件的版本呢，我看了下我的edge没有这种情况😶

firefox

**Comment by sde31c** [comment]
> 请问这是什么浏览器，浏览器的什么版本，插件的来源，插件的版本呢，我看了下我的edge没有这种情况😶

firefox v86，插件是从firefox插件商店安装的。版本就是商店里的最新版。
