### ISSUE TITLE
firefox 89 下闪烁、有时候看不到弹出菜单

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#148]
见如下视频 [a.mp4](https://fars.ee/9UiX)

不知道为啥用 github 自己的上传方式一直显示错误

**Comment by Sokwva** [comment]
还在排查问题😗

**Comment by condy0919** [comment]
tql

**Comment by Sokwva** [comment]
> tql

其实只是一条样式的问题🤣

**Comment by newtimeforC** [comment]
更新了问题还是存在,而且收不到开播推送
ubuntu 21.04
firefox 89 插件版本:1.2.10.601
edge (dev)版本 91.0.864.1  插件版本: 1.2.9.211 不闪但也收不到生放送推送

**Comment by Sokwva** [comment]
> 更新了问题还是存在,而且收不到开播推送
> ubuntu 21.04
> firefox 89 插件版本:1.2.10.601
> edge (dev)版本 91.0.864.1 插件版本: 1.2.9.211 不闪但也收不到生放送推送

闪烁问题是在1.2.10.607中修复的。
开播推送，先确保在助手设置页面中 主站配置 中的开关打开，然后在 Edge浏览器的 扩展管理页面找到助手的条目然后点击 “检查视图bg/background.html” 的超链接，然后切换到Network，观察在5分钟之内有没有网络活动，如果没有活动，去观察一下Console里面有没有相关的报错。

**Comment by Sokwva** [comment]
> 更新了问题还是存在,而且收不到开播推送
> ubuntu 21.04
> firefox 89 插件版本:1.2.10.601
> edge (dev)版本 91.0.864.1 插件版本: 1.2.9.211 不闪但也收不到生放送推送

闪烁问题是在1.2.10.607中修复的。
开播推送，先确保在助手设置页面中 主站配置 中的开关打开，然后在 Edge浏览器的 扩展管理页面找到助手的条目然后点击 “检查视图bg/background.html” 的超链接，然后切换到Network，观察在5分钟之内有没有网络活动，如果没有活动，请去观察一下Console里面有没有相关的报错。

**Comment by newtimeforC** [comment]
开关状态是打开的,以前可以收到推送,但最近不可以,
edge状态:
![2021-06-14 15-43-33 的屏幕截图](https://user-images.githubusercontent.com/26663981/121857076-cce65d80-cd27-11eb-8824-9819428e6420.png)

**Comment by Sokwva** [comment]
> 开关状态是打开的,以前可以收到推送,但最近不可以,
> edge状态:
> ![2021-06-14 15-43-33 的屏幕截图](https://user-images.githubusercontent.com/26663981/121857076-cce65d80-cd27-11eb-8824-9819428e6420.png)

简单看了下，控制台有24条报错，然后network标签页中只有一条跟直播监测没关联的活动。

**Comment by Sokwva** [comment]
看了下，有可能是因为火狐不支持带按钮的通知导致的问题

**Comment by condy0919** [comment]
现在商店版本还没有更新...

**Comment by Sokwva** [comment]
更新的话就不是我负责的了😗我只是其中一个贡献者
