### ISSUE TITLE
[Question] 评论区 Ctrl-Enter 发送回复

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#150]
以前在评论区没改版的时候是可以直接用 Ctrl-Enter 来发送的，虽然现在在插件里有提供 Shift-Enter 的方式，这部分是否可以改成 Ctrl-Enter 呢？

**Comment by condy0919** [comment]
老哥效率很高啊

**Comment by Sokwva** [comment]
😗现在有点空就改了，下个星期要准备期末了
