### ISSUE TITLE
[Feature Request] 音量提升

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#152]
类似 https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/ 它有一个功能是 Volume boost 这样就可以令当前的音量超过 100，这样在遇到了部分声音比较小的视频之后就不用来回调整系统的音量了。不知道这个能否实现呢？

**Comment by Sokwva** [comment]
你是说的这种功能吗 https://github.com/niuchaobo/acfun-helper/commit/00ad02bf746f33ac3b3af079b0131378fd981c4d

**Comment by condy0919** [comment]
原来自带了啊😯，不过开启了这个选项之后视频说无法播放，就好像被暂停了一样

**Comment by Sokwva** [comment]
那就是，坏掉了😗

**Comment by condy0919** [comment]
🥺🥺🥺

**Comment by Sokwva** [comment]
哦对了你的是什么环境？

**Comment by condy0919** [comment]
Firefox、Arch Linux

**Comment by Sokwva** [comment]
有chromium内核的浏览器吗😗

**Comment by Sokwva** [comment]
😆😆我测试了下，Edge chromium 是没问题的，应该是火狐的兼容问题。

**Comment by condy0919** [comment]
我又测试了一下是可行的

**Comment by condy0919** [comment]
![image](https://user-images.githubusercontent.com/4024656/122790583-08b29180-d2eb-11eb-8542-a947acac6aae.png)

可以像这样把它放在音量的右边吗？

**Comment by Sokwva** [comment]
> ![image](https://user-images.githubusercontent.com/4024656/122790583-08b29180-d2eb-11eb-8542-a947acac6aae.png)
> 
> 可以像这样把它放在音量的右边吗？

之所以放在播放器设置栏里面就是之前我们在开发这个功能的时候，把这个功能的入口直接放在外面，在进入网页全屏的时候，在一些小分辨率或者大缩放的系统中，会有一部分元素直接被弹幕发射按钮挡住。所以我们就尽量将以后的功能入口收纳起来放在二级菜单里面了。

**Comment by condy0919** [comment]
原来是这样，不过应该可以自适应当前的布局吧？

**Comment by Sokwva** [comment]
> 原来是这样，不过应该可以自适应当前的布局吧？

做起来挺麻烦的，但是以后如果人多了的话可以试试

**Comment by Sokwva** [comment]
> 宝

认真看直播！！！亚拉那一卡.jpg
