### ISSUE TITLE
有办法解析 2160p60 和 2160p120 的视频文件吗？

### ISSUE THREAD

**Issue by lns103** [niuchaobo/acfun-helper#153]
[https://www.acfun.cn/a/ac22096535](https://www.acfun.cn/a/ac22096535)
A站在今年早些时候支持了4k60和4k120的视频 ，但是只能在移动端app观看，并且无法缓存这两个清晰度，个人猜测可能使用的hevc编码，所以无法兼容chrome。
有没有办法解析出下载地址，本地观看，或者为支持hevc的浏览器添加相关清晰度选项
PS: edge浏览器开启 edge://flags/#edge-mf-clear-playback-win10 ，并在win10商店安装hevc扩展后，可以支持hevc视频

**Comment by Sokwva** [comment]
这么一说，我好像App端的设备都没看到过4k60的视频...
提议非常不错，虽然感觉有挺难。
