### ISSUE TITLE
firefox浏览器中界面和播放器设置部分功能无效。

### ISSUE THREAD

**Issue by sde31c** [niuchaobo/acfun-helper#160]
firefox版本: 89.0.2
助手版本: 1.2.10.624
部分功能比如评论区AC号信息弹框，评论区时间格式化及点击跳转，多P列表展开，时间轴增加章节标记等好像都无法使用了

**Comment by sde31c** [comment]
> 
> 
> AC号信息弹框 是接口改了，然后其他功能我测试了下没有问题，如果还是有问题的话可以装回旧版本试试

我刚才试了一下，其他功能是又能用了。。。

**Comment by Sokwva** [comment]
624版本的前台模块是有个钩子有问题😗
