### ISSUE TITLE
[问题报告] 播放器开始出现无限 AB 选项

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#163]
### > 要点

![image](https://user-images.githubusercontent.com/4024656/126178818-ab4a50c4-6f8f-482d-97f2-23a41c795236.png)

### > 环境信息
1. 操作系统 及其 版本： ArchLinux
2. 浏览器类型 和 版本：firefox 90
3. 助手版本：1.2.10.713

### > 复现流程 & 症状 or 其他描述

任意打开一个视频，如 [绛紫 - 东西](https://www.acfun.cn/v/ac30314758) ，然后观察播放器进度条下方的选项，会发现 AB 选项不断增多。

**Comment by Sokwva** [comment]
https://github.com/niuchaobo/acfun-helper/commit/6cde17f8bb0f0e4935313b929bcaca899c81e813

谢谢提交

**Comment by condy0919** [comment]
原来是已经修复了嘛

**Comment by Sokwva** [comment]
> 原来是已经修复了嘛

对的，还请重新拉取一下(ノﾟ∀ﾟ)ノ
