### ISSUE TITLE
[问题报告] 插件的番剧更新推送似乎是根据预定的星期几更新,来固定推送的

### ISSUE THREAD

**Issue by ironstress** [niuchaobo/acfun-helper#165]
### > 要点
我追番了<舞伎家的料理人>,每个星期的星期四都会推送告诉我更新第二集了(没认真记录过,不过周期大概就是一周一次).
### > 环境信息
1. 操作系统 及其 版本：Win10企业版 19041.330
2. 浏览器类型 和 版本：edge  92.0.902.55 
3. 助手版本：1.2.10.624

**Comment by Sokwva** [comment]
这个功能的番剧信息获取接口已经失效了，最新的版本我们已经将功能移除( ﾟ∀。)

**Comment by ironstress** [comment]
> 这个功能的番剧信息获取接口已经失效了，最新的版本我们已经将功能移除( ﾟ∀。)

插件版本是在哪里看的?不是浏览器插件管理里的版本吧

**Comment by Sokwva** [comment]
> > 这个功能的番剧信息获取接口已经失效了，最新的版本我们已经将功能移除( ﾟ∀。)
> 
> 插件版本是在哪里看的?不是浏览器插件管理里的版本吧

源码里面定义的，现在最新的版本应该是10.723

**Comment by ironstress** [comment]
> > > 这个功能的番剧信息获取接口已经失效了，最新的版本我们已经将功能移除( ﾟ∀。)
> > 
> > 
> > 插件版本是在哪里看的?不是浏览器插件管理里的版本吧
> 
> 源码里面定义的，现在最新的版本应该是10.723

能在插件的"关于&注意"里显示不?那样会方便很多

**Comment by Sokwva** [comment]
> > > > 这个功能的番剧信息获取接口已经失效了，最新的版本我们已经将功能移除( ﾟ∀。)
> > > 
> > > 
> > > 插件版本是在哪里看的?不是浏览器插件管理里的版本吧
> > 
> > 
> > 源码里面定义的，现在最新的版本应该是10.723
> 
> 能在插件的"关于&注意"里显示不?那样会方便很多

在扩展管理页面中就能看到的
