### ISSUE TITLE
[问题报告] 助手里生放送中"关注Up"列表不全

### ISSUE THREAD

**Issue by ironstress** [niuchaobo/acfun-helper#166]
### > 要点
关注Up里只会显示少数几个正在直播的Up主,貌似也是固定的少数几个.

### > 环境信息
1. 操作系统 及其 版本：Win10企业版 19041.330
2. 浏览器类型 和 版本：edge 92.0.902.55
3. 助手版本：1.2.10.624

### > 复现流程 & 症状 or 其他描述
我曾尝试删除插件,并且重置了设置.
在重置后初期,"关注Up"列表里不会显示任何正在直播的Up主
过了一段时间,"关注Up"列表能正常显示所有正在直播的Up主
到了现在,列表处于有时"会显示少数几个,有时什么都不显示"的状态.

**Comment by Sokwva** [comment]
是点击助手按钮的弹出窗口里面的列表嘛

**Comment by ironstress** [comment]
> 是点击助手按钮的弹出窗口里面的列表嘛

是的

**Comment by Sokwva** [comment]
> > 是点击助手按钮的弹出窗口里面的列表嘛
> 
> 是的

我看了下，有时候有有过推送但是之后没有了显示是因为接口返回的结果是这样，接口里面如果没有显示这些Up直播那么插件也是这么显示的。（总之就是主站的锅(`ε´ )）
