### ISSUE TITLE
[功能]能增加个深色模式吗？

### ISSUE THREAD

**Issue by SNANA51832** [niuchaobo/acfun-helper#167]
- 其他的就当开玩笑(`ε´ )，但是摘要就请务必描述一下

### > 影响研究
此功能对插件整体的结构或者它对社区环境之类可能的影响研究

**Comment by Sokwva** [comment]
( ﾟ∀。)很早就有想法了，但是现在人手不够，做不了...

**Comment by pengqian089** [comment]
可以使用DarkReader的扩展，我目前就用的这个。
