### ISSUE TITLE
[问题报告]下载一些视频变成几十字节文档文件

### ISSUE THREAD

**Issue by SeuiNeria** [niuchaobo/acfun-helper#169]
### > 要点
提交前, 确认一下以下内容:
- 我是在 报告一个Bug 或 提出功能需求。     
- 我所提交的问题可能在现在进入测试流程内的开发者版本中没有出现，也就是说，最新的测试版本通过候选成为正式版之后，我提交的问题可能就不能在新版本上出现（没有确认Pull Request的内容）。     
- 我所提出的问题在Issue里面还没有其他人提到过。     
- 我将会告知正确的环境信息。     

### > 环境信息
1. 操作系统 及其 版本：Win10专业版
2. 浏览器类型 和 版本：Firefox 79.0
3. 助手版本：1.2.10.721

### > 复现流程 & 症状 or 其他描述 
点击下载视频会突然下载完成一个几十字节的文档文件,打开后显示NULLNULLNULL,个别视频出现这种情况
.刷新或者关闭再点击视频重新试也没用

**Comment by Sokwva** [comment]
可以发个链接给我这边测试下吗

**Comment by SeuiNeria** [comment]
https://www.acfun.cn/v/ac30621024

**Comment by Sokwva** [comment]
fixed https://github.com/niuchaobo/acfun-helper/pull/168
