### ISSUE TITLE
直播弹幕

### ISSUE THREAD

**Issue by tox1ce** [niuchaobo/acfun-helper#17]
网页直播上线了  能不能保存直播弹幕  

直播时实时下载也行……  麻烦了大佬

**Comment by Sokwva** [comment]
现在网页直播还在测试阶段，还会有相当大的改变空间，我们暂时没有直接对网页直播功能增加的计划，等网页直播正式可用之后我们计划的。😗

**Comment by Sokwva** [comment]
我们已经联合 https://github.com/orzogc/acfunlive 桌面程序来做弹幕录制，功能已经加入到当前分支中，谢谢提议。
