### ISSUE TITLE
[问题报告] 点直播推送跳转的地址有问题

### ISSUE THREAD

**Issue by ironstress** [niuchaobo/acfun-helper#170]
### > 要点
试了所有都会跳转到类似这样的地址 https://live.acfun.cn/live/1229866live8111953
正常应该是 https://live.acfun.cn/live/1229866
### > 环境信息
1. 操作系统 及其 版本：Win10企业版 19041.330
2. 浏览器类型 和 版本：edge 92.0.902.67
3. 助手版本：1.2.10.624

**Comment by Sokwva** [comment]
github上最新的版本是10.723，请更新一下版本

**Comment by ironstress** [comment]
> github上最新的版本是10.723，请更新一下版本

releases里也没有啊, 要加公众号或者QQ群吗?

**Comment by Sokwva** [comment]
> > github上最新的版本是10.723，请更新一下版本
> 
> releases里也没有啊, 要加公众号或者QQ群吗?

直接拉取文件或者群，都可以

**Comment by ironstress** [comment]
> > > github上最新的版本是10.723，请更新一下版本
> > 
> > 
> > releases里也没有啊, 要加公众号或者QQ群吗?
> 
> 直接拉取文件或者群，都可以

ok了, 想问下, 既然可以直接拉取文件, 为啥不在readme"插件本体获取"里写明呢?

关于更新我有蛮多疑问的. 

      比如说, 有更新了点开图标会有提醒, 然后点击后会跳转到A站个人首页. 这就让我特别疑惑了. 我点进去完了看看文章投稿, 也没 
   写明更新内容, 一开始就让我感觉插件是不是在线更新的? 

     另外edge和chrome商店里的版本长期没有更新.

     我看readme里releases长期没更新, 只剩下加群和公众号. 
     我想我都来github安装东西了, 难道还要跳转到 另一个平台吗? 我很疑惑. 

     因为我不懂插件怎么写的, 昨天我也曾尝试直接拉取文件, readme里没写我也不知道加载的是src这个文件夹. 

最后就是我的建议了,
   我最希望的还是商店版本里能更新最新版, 至少可以在releases里看到最新版.

**Comment by Sokwva** [comment]
插件的更新是需要有相关的开发者账号的，插件更新因为开发者个人工作原因不能及时更新，这个不是我能左右的；至于离线安装的部分，我有时间会更新下；最后，我当时想的是，既然来到了github找，那么我是默认了用户是属于会使用github的，这个确实是我的问题。
