### ISSUE TITLE
视频下载编码方式问题

### ISSUE THREAD

**Issue by yangguistar** [niuchaobo/acfun-helper#174]
- 其他的就当开玩笑(`ε´ )，但是摘要就请务必描述一下

### > 摘要（描述）
下载视频后本地播放器可以播放，但是上传到服务器或者云端，则不支持H265编码方式的在线播放，希望默认下载能转为H264

### > 影响研究
更加利于传播和分享学习资料

**Comment by Sokwva** [comment]
请问一下你是用的哪种服务？是客户端解码还是服务端解码呢？

**Comment by yangguistar** [comment]
> 请问一下你是用的哪种服务？是客户端解码还是服务端解码呢？
是上传到onedrive和阿里oss,平时搭建oneindex等目录程序使用的。上传后不能在线观看，普通的video标签都不能正常播放，
