### ISSUE TITLE
[问题报告]插件异常提醒非最新版（有重大更新）

### ISSUE THREAD

**Issue by soysaucemo** [niuchaobo/acfun-helper#175]
### > 要点
更新最新版插件（1.2.12.730），软件助手主界面提示“助手有重大更新”
![image](https://user-images.githubusercontent.com/34964159/132528480-da19715f-100f-44f1-885a-d65950e4f9c7.png)

### > 环境信息
1. 操作系统 及其 版本：win10.19042 x64
2. 浏览器类型 和 版本：Edge 93.0.961.38
3. 助手版本：1.2.12.730

### > 复现流程 & 症状 or 其他描述
我用python模拟发包给代码里面的地址（post了版本信息），回复如下，看起来是服务器上的版本比对出问题了？
{
  "result": 2
}

**Comment by Sokwva** [comment]
正解，因为提供这个更新对比服务的云主机要过期了，我们正在考虑迁移更新检查服务的承载方式。虽然还没找到。。。( ﾟ∀。)

**Comment by soysaucemo** [comment]
> 正解，因为提供这个更新对比服务的云主机要过期了，我们正在考虑迁移更新检查服务的承载方式。虽然还没找到。。。( ﾟ∀。)

😂😂😂😂
是否可以考虑，直接按github的release版本获取信息，判断版本新旧由插件本地进行？
[](https://api.github.com/repos/niuchaobo/acfun-helper/releases/latest
)不过好像很久没发布release了。。。
我换了一个新的思路，看看要不要这样搞，直接访问manifest.json查看version信息。用python模拟了一下，GitHub这个api还可以。

> import requests
> import json
> import base64
> headers={
>     'content-type':'application/json',
>     'User-Agent':''
> }
> url='https://api.github.com/repos/niuchaobo/acfun-helper/contents/src/manifest.json'
> res=requests.get(url=url,headers=headers)
> json_list=json.loads(res.text)
> decode_base64=base64.b64decode(json_list['content'])
> mani_json=json.loads(decode_base64)
> print(mani_json['version'])

![image](https://user-images.githubusercontent.com/34964159/132537705-f2118933-fcba-4dde-b5e3-0ff209fb6848.png)

**Comment by Sokwva** [comment]
不错的实现方法！但是我这里有个问题：我访问Github时，偶尔会遇到被安全设备阻断的问题，无论是在家里、用移动网络、甚至在学校都会出现这样的状况，它提供的服务我们是偶尔不能访问的，所以我觉得还是将服务放到国内能稳定访问的地方更好！
