### ISSUE TITLE
弹幕怎么解析啊？找不到弹幕出现时间的字段

### ISSUE THREAD

**Issue by pengqian089** [niuchaobo/acfun-helper#179]
``` json
 {
    "likeCount": 0, // 点赞？
    "color": 16777215, //弹幕颜色
    "danmakuId": 224255629,
    "mode": 1, // 滚动模式之类的？
    "createTime": 1635914957958, //发送弹幕时间
    "rank": 5, //目前不清楚
    "danmakuImgUrl": "", //弹幕图片吗？
    "userId": 523802,
    "body": "颠勺？", //弹幕文本
    "isLike": false, //是都点赞？
    "roleId": 0,
    "danmakuStyle": 1,
    "danmakuAvatarUrl": "",// 头像
    "danmakuType": 0,//类型
    "position": 47199,//定位？
    "size": 25 //弹幕字体大小
  }
```

**Comment by condy0919** [comment]
确实没有时间…… 好像 feed 流里的时间还是自己打印的

**Comment by pengqian089** [comment]
> 确实没有时间…… 好像 feed 流里的时间还是自己打印的

挺蛋疼的，如果没有弹幕出现的时间，那么获取到的弹幕也没什么用了

**Comment by Sokwva** [comment]
不好意思，前一段时间有点儿忙。
关于时间的处理，您可以看看 https://github.com/niuchaobo/acfun-helper/blob/master/src/fg/modules/danmaku.js 的 assDanmakuProcess 函数。但是具体是个怎么解析的我不太记得了。(›´ω`‹ )

**Comment by Sokwva** [comment]
> 确实没有时间…… 好像 feed 流里的时间还是自己打印的

是根据position计算出来的

**Comment by pengqian089** [comment]
> > 确实没有时间…… 好像 feed 流里的时间还是自己打印的
> 
> 是根据position计算出来的



> 不好意思，前一段时间有点儿忙。 关于时间的处理，您可以看看 https://github.com/niuchaobo/acfun-helper/blob/master/src/fg/modules/danmaku.js 的 assDanmakuProcess 函数。但是具体是个怎么解析的我不太记得了。(›´ω`‹ )

看到啦 [这里](https://github.com/niuchaobo/acfun-helper/blob/001fe2c7d793a50bea3794163933fb1b56a857ec/src/fg/modules/danmaku.js#L81)应该就是了，谢谢了
