### ISSUE TITLE
[功能] 直播自动点赞

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#180]
### > 摘要（描述）

在观看直播的时候，能否添加一个选项选择自动点击爱心呢？

### > 灵感来源

让自己频繁出现在 feed 流里吸引[司霁](https://live.acfun.cn/live/34905158)的注意
  
### > 影响研究
此功能对插件整体的结构或者它对社区环境之类可能的影响研究

### > 细节实现

添加一个 timer 定期点击对应的 button 就行了。

**Comment by Sokwva** [comment]
然后再做一个榨干香蕉和ac币的功能就更能吸引注意了。亚娜那一卡.jpg
