### ISSUE TITLE
打开直播页面，发弹幕就会要求下载对应的 apk 

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#2]
希望可以优化一下这个发弹幕的体验

**Comment by Sokwva** [comment]
可以详细描述一下问题吗🤭

**Comment by condy0919** [comment]
https://m.acfun.cn/live/detail/20680343?platform=Android&uid=20680343

例如这个页面，用户输入弹幕后会直接下载`AcFun`手机客户端

**Comment by condy0919** [comment]
AcFun 直播 Web 版已上线，链接为 https://live.acfun.cn

**Comment by Sokwva** [comment]
我们昨天已开始对网页端做测试，谢谢你对我们插件的关注，后续我们也将会添加针对网页直播的相关功能哦😆
