### ISSUE TITLE
直播啥时候更新pc版？

### ISSUE THREAD

**Issue by yumoie** [niuchaobo/acfun-helper#20]

**Comment by Sokwva** [comment]
可以详细说明一下问题吗

**Comment by yumoie** [comment]
通过插件输uid进入直播界面，进入的是手机网页，而不是live.acfun.cn

**Comment by Sokwva** [comment]
可以报一下您所使用插件的版本号那

**Comment by heixiaobai** [comment]
> 通过插件输uid进入直播界面，进入的是手机网页，而不是live.acfun.cn

这个问题直播刚出来的时候我就修了 0e9dece4c8cfd5b2bb0c589d2f271b65ce5b2f61 ，不过浏览器插件因为审核问题还没更新

**Comment by yumoie** [comment]
版本均为商城最新版1.2.6.603，chrome和Firefox

**Comment by Sokwva** [comment]
现在还有这种情况吗

**Comment by yumoie** [comment]
有，只会转跳  m.acfun.cn/live

**Comment by heixiaobai** [comment]
@yumoie 
建议等待浏览器插件更新，或者直接使用Github上的最新代码

**Comment by aiyulu1** [comment]
chrome商店不配拥有最新版?
