### ISSUE TITLE
请问如何禁用直播通知？

### ISSUE THREAD

**Issue by Ayx03** [niuchaobo/acfun-helper#208]
![image](https://user-images.githubusercontent.com/75155322/212115387-ab446795-5b55-403a-9d1a-b845a2a7c636.png)

**Comment by Sokwva** [comment]
设置->直播->关注直播推送->关注Up开播提醒

**Comment by Ayx03** [comment]
@Sokwva Thanks!
<extension://lbnimimllmcdmojehbgndnebjafgnjfk/bg/options.html#tab6>
