### ISSUE TITLE
右键开关和默认最高画质+夜间模式、小建议

### ISSUE THREAD

**Issue by catshitz** [niuchaobo/acfun-helper#26]
1. 添加右键开关以能够选择是否显示浏览器右键acfun助手选项 如”使用acfun搜索“
2. 1080+/1080p60f A站默认记忆上一视频画质 当下一视频最高画质不同 默认自动画质往往并非最高 请加入“默认自动选择当前视频最高画质”
3. 尝试黑化acfun 增加夜间模式功能
4. 网页全屏时助手标签会浮动在视频右上上层 阻挡小块视频 请求修复

**Comment by Sokwva** [comment]
emmmm请问默认最高画质对猴山的带宽占用是不是会有点高啊。

**Comment by Sokwva** [comment]
问题4已通过pr，下个正式版将会修复此问题，请耐心等待，或者直接pull代码至本地，覆盖安装。

**Comment by Sokwva** [comment]
你好，因为开发组现阶段没有UI设计的同志、同时，适配也需要考虑太多特别的元素（比如黑白的经典AC娘表情包和彩娘），开发组人手并不足够，所以我们近期不会考虑夜间模式。谢谢你的提问。
