### ISSUE TITLE
番剧页面不支持下载吗

### ISSUE THREAD

**Issue by xlx034** [niuchaobo/acfun-helper#34]
如题

**Comment by Sokwva** [comment]
你好，番剧不支持下载，也不会考虑去支持下载，谢谢提问。

**Comment by xlx034** [comment]
> 你好，番剧不支持下载，也不会考虑去支持下载，谢谢提问。

明白

**Comment by Sokwva** [comment]
谢谢体谅，我们是尽量以不伤害猴山利益为前提开发的，如果这为你造成了不便我们先代表开发组说声道歉。
