### ISSUE TITLE
[Enhancement] 生放送提醒添加UID时能否从关注中构造一个列表以供选择

### ISSUE THREAD

**Issue by condy0919** [niuchaobo/acfun-helper#45]
我不信有人没有关注一个`up`但是却要收听他的直播提醒

**Comment by Sokwva** [comment]
从主站的个人关注中提取内容然后自行选择关注的Up？

**Comment by condy0919** [comment]
> 从主站的个人关注中提取内容然后自行选择关注的Up？

是的

**Comment by Sokwva** [comment]
> > 从主站的个人关注中提取内容然后自行选择关注的Up？
> 
> 是的

收到，已加入开发列表，谢谢提交问题
