### ISSUE TITLE
助手的按钮选项能放在播放器下面吗？

### ISSUE THREAD

**Issue by 15372843021** [niuchaobo/acfun-helper#49]
网页全屏观看很碍眼

**Comment by niuchaobo** [comment]
理论上，当播放器全屏时助手按钮会自动隐藏，不过在某些时候会失效，我会在以后修复这个问。

**Comment by Sokwva** [comment]
https://github.com/niuchaobo/acfun-helper/commit/6977c2f6663674d187de09431c09dedd6d90d480
