### ISSUE TITLE
隐私协议乱码

### ISSUE THREAD

**Issue by SingSky** [niuchaobo/acfun-helper#68]
环境：Chrome 84.0.4147.105 正式版
插件版本：1.2.6.603
插件安装自：Chrome扩展商店
问题：在助手的“选项-关于/注意”点击“隐私协议”Privacy链接，在新页面中打开的md文件乱码。
见图：https://i.loli.net/2020/08/05/LTIqJBWPgV16HCl.png

**Comment by Sokwva** [comment]
谢谢反馈，已找到问题；这里的连接应该指向html文件，而不是md，可能是之前的pr冲突被覆盖了。

**Comment by Sokwva** [comment]
现在最新的版本应该是705，里面包含了大量的修复，建议更新一下哦。
