### ISSUE TITLE
插件的配置似乎没有保存

### ISSUE THREAD

**Issue by tyh97** [niuchaobo/acfun-helper#72]
firefox浏览器
每次插件更新后，插件的配置、又回到了初始状态，好像并没有保存下来。

**Comment by Sokwva** [comment]
哪个平台的什么系统的什么版本下的火狐浏览器？插件是怎样的渠道安装的呢？这是每次更新都出现的状况吗？在同一台电脑上的其他浏览器上面有类似的状况吗？

**Comment by tyh97** [comment]
> 
> 
> 哪个平台的什么系统的什么版本下的火狐浏览器？插件是怎样的渠道安装的呢？这是每次更新都出现的状况吗？在同一台电脑上的其他浏览器上面有类似的状况吗？
window10平台，用的是firefox，版本号是1.2.7.809，直接在应用商店里装的。就是播放器设置里的观影模式关灯适配暗色设置，我每次都是关了的，但是更新后好像又开着了。暂时只看到这个问题。

**Comment by Sokwva** [comment]
> > 哪个平台的什么系统的什么版本下的火狐浏览器？插件是怎样的渠道安装的呢？这是每次更新都出现的状况吗？在同一台电脑上的其他浏览器上面有类似的状况吗？
> > window10平台，用的是firefox，版本号是1.2.7.809，直接在应用商店里装的。就是播放器设置里的观影模式关灯适配暗色设置，我每次都是关了的，但是更新后好像又开着了。暂时只看到这个问题。

你好，我在这边测试了一下，不是代码的问题，请检查一下同样的代码在你电脑上其他浏览器的表现吧。

**Comment by tyh97** [comment]
好像解决了，没有问题了
